---
apiVersion: v1
kind: Service
metadata:
  name: amber-backend
  namespace: khing
  labels:
    app: amber-hour
    component: backend
spec:
  type: ClusterIP
  selector:
    app: amber-hour
    component: backend
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http

---
apiVersion: v1
kind: Service
metadata:
  name: amber-frontend
  namespace: khing
  labels:
    app: amber-hour
    component: frontend
spec:
  type: ClusterIP
  selector:
    app: amber-hour
    component: frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
